MS_Django/ms/ms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('msApp.urls')),
    path('admin/', admin.site.urls),
]

MS_Django/ms/msApp/urls.py
from unicodedata import name
from django.urls import path
from django.conf import settings
from . import views

app_name = 'msApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('login/', views.logins, name='logins'),
    path('logina/', views.logina, name='logina'),
    path('functions/', views.functions, name='functions'),
    path('attendance/', views.attendance, name='attendance'),
    path('employee/', views.employee, name='employee'),
    path('homepage/', views.homepage, name='homepage'),
    path('admin/', views.admin, name='admin'),
    path('users/', views.users, name='users'),
    path('payroll/', views.payroll, name='payroll'),
    path('logoutAdmin/', views.logoutAdmin, name="logout"),
    path('logoutUser/', views.logoutUser, name="logoutu"),
    path('pdf_generator/', views.pdf_generator, name="pdf_generator")

]

MS_Django/ms/msApp/models.py
from ast import mod
from django.db import models
import datetime
import os

# Create your models here.

# def filename(request, filename):
#     old_filename = filename
#     timenow = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
#     filename = "%s%s", (timenow, old_filename)
#     return os.path.join('uploads/', filename)

# class admin(models.Model):
#     idno = models.CharField(max_length=15, null=False)
#     fullname = models.CharField(max_length=15, null=False)
#     username = models.CharField(max_length=15, null=False)

class Employee(models.Model):
    firstname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)


class Attendance(models.Model):
    dates = models.DateField()
    employee = models.CharField(max_length=100)
    timein = models.TimeField()
    timeout = models.TimeField()
    username = models.CharField(max_length=100)
    totalrecord = models.CharField(max_length=100)
    num = models.IntegerField()

class Payroll(models.Model):
    employee = models.CharField(max_length=100)
    total = models.IntegerField()
    num = models.IntegerField()
    totalrecord = models.CharField(max_length=100)
    dates = models.DateField()

MS_Django/ms/msApp/forms.py
from dataclasses import field, fields
from pyexpat import model
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name','last_name','username', 'password1', 'password2','email']


class EmployeeForm(forms.ModelForm):
	class Meta:
		model = Employee
		fields = '__all__'
		

class AttendanceForm(forms.ModelForm):
	class Meta:
		model = Attendance
		fields = '__all__'

class PayrollForm(forms.ModelForm):
	class Meta:
		model = Payroll
		fields = '__all__'

MS_Django/ms/msApp/views.py
from email import message
from re import L
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *


from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import io

from django.http import FileResponse

from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

from django.core.mail import send_mail
from django.conf import settings



installed_apps =['msApp']

# Create your views here.
def index(request):
    if request.method == "POST":
        mes_name = request.POST['name']
        mes_email = request.POST['email']
        message = request.POST['message']

        #send an email
        send_mail(
            mes_name, #subject
            message, #message
            mes_email, #from email
            ['joycelyncorpuz28@gmail.com'], #to email
        )
        return render(request, 'msApp/index.html', {'mes_name':mes_name})
    else:
        return render(request, 'msApp/index.html',{})

def logins(request):
    if request.user.is_authenticated and request.user.is_staff:
        return redirect ('msApp:attendance')
    if request.method == 'POST':
        users = request.POST.get('username')
        passw = request.POST.get('password') 
        request.session['username'] = users
        user = authenticate(request, username=users,password=passw)
 
        if user is not None:
            login(request, user)

            if user.is_staff:
                return redirect('msApp:attendance')
            else:
                messages.info(request,'Invalid Credentials!')
                return redirect('msApp:logins')

    form = CreateUserForm()
    if request.method == 'POST':
        email = request.POST["email"] # success email registration
        email=email # success email registration
        form = CreateUserForm(request.POST)
        messages.info(request,'Something went wrong!')
        form.instance.is_staff = True
        if form.is_valid():
            subject = 'Management System' # success email registration
            message = 'Welcome and Thank you for Registering in Management System.This is auto generated message.Do not reply...' # success email registration
            recipient = form.cleaned_data.get('email') # success email registration
            send_mail(subject, message, settings.EMAIL_HOST_USER, [recipient], fail_silently=False) # success email registration
            messages.info(request,'Successfully Registered your Account!')
            form.save()
            return redirect('msApp:logins')

    return render(request, 'msApp/login.html')

def logina(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect ('msApp:homepage')
    if request.method == 'POST':
        users = request.POST.get('username')
        passw = request.POST.get('password') 
        request.session['username'] = users
        user = authenticate(request, username=users,password=passw)
 
        if user is not None:
            login(request, user)

            if user.is_superuser:
                return redirect('msApp:homepage')
            else:
                messages.info(request,'Invalid Credentials!')
                return redirect('msApp:logina')

    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        messages.info(request,'Something went wrong!')
        form.instance.is_superuser = True
        if form.is_valid():
            messages.info(request,'Successfully Registered your Account!')
            form.save()
            return redirect('msApp:logina')

    return render(request, 'msApp/logina.html')

def functions(request):
    return render(request, 'msApp/functions.html')

@login_required(login_url='msApp:logins')
def attendance(request):
    if request.user.is_authenticated and request.user.is_staff:
        userData = request.user
        checkForm = User.objects.filter(username=userData).values()
        getDataAttendance = Attendance.objects.filter(username=userData)
        getRandomNum = request.POST.get('nums')
        attendance_del = Attendance.objects.filter(num=getRandomNum)
        payroll_del = Payroll.objects.filter(num=getRandomNum)

        list1 = []
        list2 = []

        for l in checkForm:
            list1.append(l)

        for a in getDataAttendance:
            list2.append(a)

        formattendance = AttendanceForm(request.POST or None)
        formpayroll = PayrollForm(request.POST or None)
        
        if request.method == 'POST':
            if formattendance.is_valid() and formpayroll.is_valid():
                messages.info(request,'Successfully Added the Attendance!')
                formattendance.save()
                formpayroll.save()
                return redirect('msApp:attendance')

        
        if request.method == "POST":
            messages.info(request,'Successfully Deleted!')
            attendance_del.delete()
            payroll_del.delete()
            return redirect('msApp:attendance')

        context = {
            'form': list1,
            'attendance': list2
        }
        return render(request, 'msApp/attendance.html', context)
    return redirect ('msApp:logins')

@login_required(login_url='msApp:logina')
def homepage(request):
    if request.user.is_authenticated:
        return render(request, 'msApp/homepage.html')
    return redirect ('msApp:logina')

@login_required(login_url='msApp:logina')
def payroll(request):
    if request.user.is_authenticated:
        getDataPayroll = Payroll.objects.all()

        context = {
            'payroll': getDataPayroll
        }
        return render(request, 'msApp/payroll.html', context)
    return redirect ('msApp:logina')

def pdf_generator(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 20)

    d1 = request.POST.get('employeeId') 
    d2 = request.POST.get('employeeName') 
    d3 = request.POST.get('employeeDate') 
    d4 = request.POST.get('employeeTime') 
    d5 = request.POST.get('employeeDeduction') 
    d6 = request.POST.get('employeeTotal')

    print(d1, d2, d3, d4, d5, d6)
    lines = [
        "Payroll Details:",
        "",
        d1,
        d2,
        d3,
        d4,
        d5,
        d6
    ]

    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename="Payroll_Detail_for_"+d2+".pdf")

@login_required(login_url='msApp:logina')
def employee(request):
    if request.user.is_authenticated:
        getDataEmployee = Employee.objects.all()
        formemployee = EmployeeForm(request.POST or None)
        buy_id = request.POST.get('id')
        employee_del = Employee.objects.filter(id=buy_id)
        
        if request.method == 'POST':
            if formemployee.is_valid():
                messages.info(request,'Successfully Added the Employee!')
                formemployee.save()
                return redirect('msApp:employee')

        if request.method == "POST":
            messages.info(request,'Successfully Deleted!')
            employee_del.delete()
            return redirect('msApp:employee')

        context = {
            'employee': getDataEmployee
        }

        return render(request, 'msApp/employee.html', context)
    return redirect ('msApp:logina')

@login_required(login_url='msApp:logina')
def admin(request):
    if request.user.is_authenticated:
        getDataAdmin = User.objects.filter(is_superuser=True)

        admin_id = request.POST.get('id')
        admin_del = User.objects.filter(id=admin_id)

        if request.method == "POST":
            messages.info(request,'Successfully Deleted!')
            admin_del.delete()
            return redirect('msApp:admin')

        context = {
            "admin": getDataAdmin
        }
        return render(request, 'msApp/admin.html', context)
    return redirect ('msApp:logina')

@login_required(login_url='msApp:logina')
def logoutAdmin(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('msApp:logina')

@login_required(login_url='msApp:logina')
def users(request):
    if request.user.is_authenticated:
        getDataUser = User.objects.filter(is_staff=True)

        user_id = request.POST.get('id')
        user_del = User.objects.filter(id=user_id)

        if request.method == "POST":
            messages.info(request,'Successfully Deleted!')
            user_del.delete()
            return redirect('msApp:users')

        context = {
            "user": getDataUser
        }
        return render(request, 'msApp/users.html', context)
    return redirect ('msApp:logina')

@login_required(login_url='msApp:logins')
def logoutUser(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('msApp:logins')

MS_Django/ms/msApp/templates/msApp/admin.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{%static 'css/styles.css' %}">

  <title>Management System - Admin</title>
</head>

<body id="body-pd" class="bg-light">
  <header class="header" id="header">
    <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
  </header>
  <div class="l-navbar" id="nav-bar">
    <nav class="nav">
      <div>
        <a href="{% url 'msApp:homepage' %}" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Management <br> System</span> </a>
        <div class="nav_list">
            <a href="{% url 'msApp:homepage' %}" class="nav_link"> <i class='bx bx-home-alt nav_icon'></i> <span class="nav_name">Home</span> </a>
            <a href="{% url 'msApp:payroll' %}" class="nav_link"> <i class='bx bx-note nav_icon'></i> <span class="nav_name">Payroll List</span> </a>
            <a href="{% url 'msApp:employee' %}" class="nav_link"> <i class='bx bx-user-pin nav_icon'></i> <span class="nav_name">Employee List</span> </a>
            <a href="{% url 'msApp:users' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users List</span> </a>
            <a href="{% url 'msApp:admin' %}" class="nav_link active"> <i class='bx bx-user-circle nav_icon'></i> <span class="nav_name">Admin List</span> </a>

          </div>
      </div>
      <a href="{% url 'msApp:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log out</span> </a>
    </nav>
  </div>
  <!--Container Main start-->
  <div class="height-100">
    <div class="row">
      <div class="col-md">
        <h1><b>Management System Admin</b></h1>
      </div>
      <div class="col-md clock">
        <span id="LiveTime" class="badge bg-warning text-dark" style="font-size: 20px;"></span>
      </div>
    </div>

    <!-- TABLE ADMIM -->
    <div class="mt-5">
      <div class="row">
        <div class="col-lg-7">
          <h4 class="mt-1 mb-1">Admin List</h4>
        </div>
        <div class="col-lg-5" style="display: inline-flex;">
          <input type="text" class="form-control" id="searchUsers" onkeyup="searchUsers()"  placeholder="Search...">
          <span class="input-group-text bg-danger text-white"><i class='bx bx-search-alt-2 nav_logo-icon'></i></span>
        </div>
      </div>
      <div class="tableData overflow-auto">
        <table class="table mt-4 table-hover" id="myTable">
          <thead class="table-dark">
            <tr>
              <th scope="col">Full Name</th>
              <th scope="col">Username</th>
              <th scope="col">Email</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for a in admin %}  
            <tr>
              <td>{{ a.first_name }} {{ a.middle_name }} {{ a.last_name }}</td>
              <td>{{ a.username }}</td>
              <td>{{ a.email }}</td>
              <td><button type="button" data-bs-toggle="modal" class="btn btn-danger" data-bs-target="#modalDelete{{ a.id }}">Delete</button></td>
            </tr>

            <!-- MODAL DELETE -->
            <div class="modal fade" id="modalDelete{{ a.id }}" tabindex="-1" role="dialog" aria-labelledby="modalDelete" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Are you sure you want to delete?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <div class="text-center">
                      <form action="" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ a.id }}" >
                        <h3>You are now deleting admin: {{ a.first_name }} {{ a.middle_name }} {{ a.last_name }}</h3>
                        <br>
                        <button type="submit" class="btn btn-danger" name="deleteUser">Yes I'm sure</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No not now</button>
                      </form>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="no-result-div mt-4 text-center" id="no-search">
        <div class="div">
          <img src="{%static 'images/search.svg'%}" alt="">
          <h4 class="mt-3">Search not found...</h4>
          <p>Search for fullnames, usernames, emails and etc.</p>
        </div>
      </div>
    </div>
  </div>




  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/search.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  {% for message in messages %}
  <script>
      swal("{{message}}","");
  </script>
  {% endfor %}

</body>

</html>

MS_Django/ms/msApp/templates/msApp/homepage.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{%static 'css/styles.css' %}">
  <title>Management System - Homepage</title>
</head>

<body id="body-pd" class="bg-light">
  <header class="header" id="header">
    <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
  </header>
  <div class="l-navbar" id="nav-bar">
    <nav class="nav">
      <div>
        <a href="{% url 'msApp:homepage' %}" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Management <br> System</span> </a>
        <div class="nav_list">
            <a href="{% url 'msApp:homepage' %}" class="nav_link" active> <i class='bx bx-home-alt nav_icon'></i> <span class="nav_name">Home</span> </a>
            <a href="{% url 'msApp:payroll' %}" class="nav_link"> <i class='bx bx-note nav_icon'></i> <span class="nav_name">Payroll List</span> </a>
            <a href="{% url 'msApp:employee' %}" class="nav_link"> <i class='bx bx-user-pin nav_icon'></i> <span class="nav_name">Employee List</span> </a>
            <a href="{% url 'msApp:users' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users List</span> </a>
            <a href="{% url 'msApp:admin' %}" class="nav_link"> <i class='bx bx-user-circle nav_icon'></i> <span class="nav_name">Admin List</span> </a>

          </div>
      </div>
      <a href="{% url 'msApp:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log out</span> </a>
    </nav>
  </div>
  <!--Container Main start-->
  <div class="height-100">
    <div class="row">
      <div class="col-md">
        <h1><b>Welcome Back Adminstrator!</b></h1>
      </div>
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

MS_Django/ms/msApp/templates/msApp/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

  <head>
    <title>Management System</title>
  </head>

<style>
  body{
    background-image: linear-gradient(to right top, #6b0e0e, #530d14, #3a0d15, #220b0f, #000000);
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>

<body>
  <form method="post">
    {%csrf_token%}
    <div class="col-md-12 mt-4 mb-2" style="text-align: left;">
      <h1><a href="{% url 'msApp:logins' %}" class="nav_link"> <span class="nav_name">Login for Employee</span> </a></h1>
      <div>
      </div>
      <h1><a href="{% url 'msApp:logina' %}" class="nav_link"> <span class="nav_name">Login for Admin</span> </a><h1>
    <div>
    <div class="col-md-12 mt-4 mb-2" style="text-align: center;">
      <br/><br/><br/>
      <br/><br/><br/>
      <br/><br/><br/>

      {% if mes_name%}
      <center>
        <h3> Thanks {{mes_name}}!</h3>
        <p> We will received your email and will respond shortly...</p>
      </center>
      {%else%}
    <div>
      <h3>Contact us here:</h3>
    </div>
          <form action="/index">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" placeholder="Your name.." style="height:50px"></textarea>
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" placeholder="Your email.." style="height:50px"></textarea>
            <label for="message">Message:</label>
            <input type="message" name="message" placeholder="Write something.." style="height:50px"></textarea>
            <input type="submit" value="Submit">
          </form>
      {%endif%}
    </form>
  </body>
</html>

MS_Django/ms/msApp/templates/msApp/payroll.html
{% load static %}
<!DOCTYPE html> 
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{%static 'css/styles.css' %}">
  <title>Management System</title>
</head>

<body id="body-pd" class="bg-light">
  <header class="header" id="header">
    <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
  </header>
  <div class="l-navbar" id="nav-bar">
    <nav class="nav">
      <div>
        <a href="{% url 'msApp:homepage' %}" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Management <br> System</span> </a>
        <div class="nav_list">
            <a href="{% url 'msApp:homepage' %}" class="nav_link"> <i class='bx bx-home-alt nav_icon'></i> <span class="nav_name">Home</span> </a>
            <a href="{% url 'msApp:payroll' %}" class="nav_link active"> <i class='bx bx-note nav_icon'></i> <span class="nav_name">Payroll List</span> </a>
            <a href="{% url 'msApp:employee' %}" class="nav_link"> <i class='bx bx-user-pin nav_icon'></i> <span class="nav_name">Employee List</span> </a>
            <a href="{% url 'msApp:users' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users List</span> </a>
            <a href="{% url 'msApp:admin' %}" class="nav_link"> <i class='bx bx-user-circle nav_icon'></i> <span class="nav_name">Admin List</span> </a>

          </div>
      </div>
      <a href="{% url 'msApp:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log out</span> </a>
    </nav>
  </div>

  <!--Container Main start-->
<div class="height-100">
  <div class="row">
    <div class="col-md">
      <h1><b>Management System Payroll</b></h1>
    </div>
    <div class="col-md clock">
      <span id="LiveTime" class="badge bg-warning text-dark" style="font-size: 20px;"></span>
    </div>
  </div>

  <!-- TABLE PAYROLL -->
  <div class="mt-5">
    <div class="row">
      <div class="col-lg-7">
        <h4 class="mt-1 mb-1">Payroll List</h4>
      </div>
      <div class="col-lg-5" style="display: inline-flex;">
        <input type="text" class="form-control" id="searchPayroll" onkeyup="searchPayroll()" placeholder="Search name...">
        <span class="input-group-text bg-danger text-white"><i class='bx bx-search-alt-2 nav_logo-icon'></i></span>
      </div>
    </div>
    <div class="tableData overflow-auto">
      <table class="table mt-4 table-hover" id="myTableP">
        <thead class="table-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Total</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for p in payroll %} 
            <tr>
              <td>{{ p.employee }}</td>
              <td>P {{ p.total }}</td>
              <td><button type="button" data-bs-toggle="modal" class="btn btn-danger" data-bs-target="#modalView{{ p.id }}">View</button></td>
            </tr>

            <!-- MODAL VIEW -->
            <div class="modal fade" id="modalView{{ p.id }}" tabindex="-1" role="dialog" aria-labelledby="modalDelete" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Salary Slip</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body text-center">
                      <form action="{% url 'msApp:pdf_generator' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="name" name="APname">
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeId" value="Employee I.D: {{ p.id }}" readonly>
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeName" value="Employee: {{ p.employee }}" readonly>
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeDate" value="Release Date: {{ p.dates }}" readonly>
                        <p>-------------------------------------------------------</p>
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeTime" value="Worked Hour/Day: {{ p.totalrecord }}" readonly>
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeDeduction" value="Deduction: 0" readonly>
                        <input class="text-center" style="border: none; font-size: 25px" name="employeeTotal" value="Total Salary: P{{ p.total }}" readonly>
                        <br><br>
                        <button type="submit" id="savePdf" class="btn btn-danger" >Save as Pdf</button>
                      </form>
                  </div>
                </div>
              </div>
            </div>

            
            {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="no-result-div mt-4 text-center" id="no-searchP">
        <div class="div">
          <img src="{%static 'images/search.svg'%}" alt="">
          <h4 class="mt-3">Search not found...</h4>
          <p>Search for fullnames, usernames, emails and etc.</p>
        </div>
      </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/search.js' %}"></script>
  <script src="{% static 'js/jspdf.min.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  {% for message in messages %}
  <script>
      swal("{{message}}","");
  </script>
  {% endfor %}

  <!-- <script>
    $(document).ready(function(){
      $('#savePdf').click(function genPDF() {
        a1 = $('#employeeId').val()
        a2 = $('#employeeName').val()
        a3 = $('#employeeDate').val()
        a4 = $('#employeeTime').val()
        a5 = $('#employeeDeduction').val()
        a6 = $('#employeeTotal').val()
        var doc = new jsPDF();
        doc.text(80, 20, "Payroll Details:");
        doc.text(20, 40, a1);
        doc.text(20, 50, a2);
        doc.text(20, 60, a3);
        doc.text(20, 70, a4);
        doc.text(20, 80, a5);
        doc.text(20, 90, a6);
        doc.save('Payroll data for : ' + a2 + '.pdf');
      })
    }) -->
  </script>
</body>

</html>